Rename and fix test case
This test case too was not running because there is another test case with the same name in this file. That issue was introduced in: https://github.com/activeadmin/inherited_resources/commit/3a4894e7#diff-f18627fee27eba459b80262e6a0f1278

If you search for "test_assigns_country_and_state_and_city_on_create" you'll see it listed twice in that file.

Once the test case name is unique, it runs but it will fail with an error of:

```
NoMethodError: undefined method `all' for City:Class
```

I wasn't sure how to correct this but I searched the repository for "undefined method all" and on this page: https://github.com/activeadmin/inherited_resources/search?q=undefined+method+all&type=Issues I found the PR: https://github.com/activeadmin/inherited_resources/pull/116 I then noticed other tests for get requests on index actions that used `expects(:scoped)` instead. Exact same style setup but this was just wrong and since it wasn't running we didn't know.